### ISSUE TITLE
`SPC k` is ignored in magit.

### ISSUE THREAD

**Issue by amano-kenji** [meow-edit/meow#722]
```
(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-overwrite-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; SPC j/k will run the original command in MOTION state.
   '("j" . "H-j")
   '("k" . "H-k")
   ;; Use SPC (0-9) for digit arguments.
```
`SPC k` is supposed to call `magit-discard` on magit, but it is simply ignored. I think `SPC j` is also ignored in magit.

**Comment by accelbread** [comment]
I ran into same issue. Removing `'("j" . "H-j")` and `'("k" . "H-k")` fixed it for me.

**Comment by amano-kenji** [comment]
What do `H-j` and `H-k` mean?

**Comment by DogLooksGood** [comment]
They are no longer needed.

**Comment by amano-kenji** [comment]
Since documentation is fixed, I think this issue can be closed.

**Comment by shfx** [comment]
I don't have any `meow-leader-define-key`, have couple of `meow-motion-define-key`'s defined and still can't use `SPC k` in magit. Any idea why?

**Comment by amano-kenji** [comment]
After removing  `'("j" . "H-j")` and `'("k" . "H-k")`, `SPC k` works properly in magit for me.
